- name: Restart service
  ansible.builtin.systemd:
    service: 3proxy
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  when: not ansible_check_mode
  listen: 'proxy3 : restart service'

- name: Reload Uncomplicated Firewall service
  community.general.ufw:
    state: reloaded
  become: true
  listen: 'proxy3 : reload firewall'
